kersulis/__init__.py
from flask import Flask
from flask_assets import Environment, Bundle
from flask_images import Images
from kersulis.views import mod as kersulis_main


app = Flask(__name__)
app.config.from_object('kersulis.config.FlaskConfig')
images = Images(app)

app.register_blueprint(kersulis_main)

assets = Environment(app)
assets.register('img_favicon',
                Bundle('images/favicon.png', output='gen/favicon.png'))

kersulis/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template


mod = Blueprint('kersulis_main', __name__)


@mod.route('/')
def index():
    return render_template('index.html')


@mod.route('/acquaint')
def acquaint():
    return render_template('acquaint/acquaint.html')


@mod.route('/statement')
def statement():
    return render_template('acquaint/statement.html')


@mod.route('/acknowledgments')
def acknowledgments():
    return render_template('acquaint/acknowledgments.html')


@mod.route('/network')
def network():
    return render_template('acquaint/network.html')


@mod.route('/construction')
def construction():
    return render_template('under_construction.html')


@mod.route('/projects/<_project>')
def project(_project):
    print(_project)
    return render_template(
        'projects/{}.html'.format(_project),
        image_width=1280,
        image_quality=40,
        project=_project
    )


@mod.route('/humans.txt')
def humans():
    return render_template('humans.html')


@mod.route('/copyright.txt')
def copyright():
    return render_template('copyright.txt')

kersulis/templates/acquaint/acknowledgments.html
{% extends 'base.html' %}
{% block title %}: acknowledgments{% endblock %}
{% block main %}
  <p>Deep thanks to Sergio Torres-Torres for years-long
    discourse about art, philosophy, and life in all its
    complexity. The development of my work would not have
    occurred without him.</p>

  <p>This website came out of a conversation with Nathan Matteson
    who understood the abstract concepts and visual thinking behind
    my work, and a simultaneous understanding of how online media
    works. Crucial to any translation is a balance between fidelity
    and transparency. Conversations grew over time as did our
    ability to build a digital framework that holds fast to the
    antagonism between the discrete object and the continuous image.
    Editing texts and images to work well together took far more
    time than expected!</p>

  <p>Peter Lynde, who’s generosity only begins with the photography
    used in my work and for most of the installation shots used on
    this site. The nuances in my work depend heavily upon tactile
    perception. Rather than this being an obstacle, it was seen as
    a challenge: making it hard to discern authorship at times.</p>

  <p>Thanks to Mary Leclère for offering her understanding of my
    work, conversing about art historical references, and articulating
    difficult concepts that would have been stumbled over if it
    were not for her persistence with explanation.</p>

  <ul class='acquaint list root'>
    <li><a class=email href=mailto:nickersulis@yahoo.com>
      nickersulis@yahoo.com</a></li>
    <li><a href={{ url_for('kersulis_main.statement') }}>
      artist's statement
    </a></li>
    <li><a href={{ url_for('kersulis_main.network') }}>
      network
    </a></li>
    <li><a href={{ url_for('kersulis_main.acquaint') }}>
      artist's bio
    </a></li>

  </ul>

{% endblock %}

kersulis/templates/acquaint/acquaint.html
{% extends 'base.html' %}
{% block main %}

  <p>Nicholas Kersulis is an artist who works in Los Angeles.
    He received his BFA from CalArts and his MFA from UCLA
    in the Interdisciplinary Studio Specialization. He has had
    solo exhibitions in Los Angeles and Houston, and has been in
    several group exhibitions internationally, including the
    MexiCali Biennial 09/10, the 2008 Houston Area Exhibition
    at the Blaffer Museum of Art, Learning by Doing: 25 Years
    of the Core Program at the Museum of Fine Arts, Houston, and
    One Hundred Artists See God (Independent Curators International).
    He has been a participant in residency fellowships including
    The Banff Centre of the Arts; the Core Artist in Residence
    Fellowship at The Museum of Fine Arts, Houston, and the
    Ucross Foundation Residency Program.</p>

  <ul class='acquaint list root'>
    <li><a class=email href=mailto:nickersulis@yahoo.com>
      nickersulis@yahoo.com</a></li>
    <li><a href={{ url_for('kersulis_main.statement') }}>
      artist's statement
    </a></li>
    <li><a href={{ url_for('kersulis_main.network') }}>
      network
    </a></li>
    <li><a href={{ url_for('kersulis_main.acknowledgments') }}>
      acknowledgments
    </a></li>

  </ul>
{% endblock %}

kersulis/templates/acquaint/network.html
{% extends 'base.html' %}
{% block title %}: network{% endblock %}
{% block main %}
  <ul class='network list root'>
    <li><a href=https://www.banffcentre.ca/>
      Banff Centre of the Arts</a></li>
    <li><a href=https://www.biennialwatch.com/>
      Biennial Watch</a></li>
    <li><a href=http://blafferartmuseum.org/>
      Blaffer Museum</a></li>
    <li><a href=https://calarts.edu/>
      CalArts</a></li> 
    <li><a href=http://secondarytext.com/>
      Anthony Carfello</a></li>
    <li><a href=http://sookim.org/>
      Soo Kim</a></li>
    <li><a href=http://limin.al/>
      Limin.al</a></li>
    <li><a href=http://skeptic.ist>
      Nathan Matteson</a></li>
    <li><a href=http://mexicalibiennial.org/200910-2/>
      MexiCali Biennial 2009/10</a></li>
    <li><a href=https://en.wikipedia.org/wiki/Dwayne_Moser>
      Dwayne Moser</a></li>
    <li><a href=https://www.mfah.org/fellowships/core-program/>
      Museum of Fine Arts Houston Core Program</a></li>
    <li><a href=https://www.youtube.com/watch?v=_cz5zm5z_b0>
      Otis Department of Fine Art Visiting Artist</a></li>
    <li><a href=https://www.art.ucla.edu/interdisciplinary-studio/alumni.html>
      UCLA Interdisciplinary Studio Alumni</a></li>
    <li><a href=https://en.wikipedia.org/wiki/Mexicali_Biennial>
      Amy Pederson-Converse</a></li>
    <li><a href=https://art.northwestern.edu/visiting-artists/sergio-torres-torres-2010
           style=padding-right:.2rem>
        Sergio
      </a><a href=http://www.remahortmannfoundation.org/project/sergio-torres-torres/
         style=padding-left:.2rem>
        Torres–Torres</a></li>
    <li><a href=https://www.hatchfund.org/showcase/nicholas_kersulis_recent_works>
      United States Artists Project Grant</a></li>
    <li><a href=http://www.ucrossfoundation.org/residency-program/>
      Ucross Foundation Residency Program</a></li>
    <li><a href=http://www.sergiobromberg.com/art-prostituta-1/>
      Venice6114</a></li>
    <li><a href=https://www.printedmatter.org/catalog/39607/>
      X-tra The Benefit of Friends Collected, Vol. 2</a></li>
    <li><a href=http://art.yale.edu/Norfolk>
      Yale Norfolk</a></li>
  </ul>

  <ul class='acquaint list root'>
    <li><a class=email href=mailto:nickersulis@yahoo.com>
      nickersulis@yahoo.com</a></li>
    <li><a href={{ url_for('kersulis_main.statement') }}>
      artist's statement
    </a></li>
    <li><a href={{ url_for('kersulis_main.acquaint') }}>
      artist's bio
    </a></li>
    <li><a href={{ url_for('kersulis_main.acknowledgments') }}>
      acknowledgments
    </a></li>

  </ul>

{% endblock %}

kersulis/templates/acquaint/statement.html
{% extends 'base.html' %}
{% block title %}: artist's statement{% endblock %}
{% block main %}
  <p>Nicholas Kersulis’ practice applies systems of organization
    to cultural artifacts through formal devices such as montage,
    accretion, and erasure, and through the conventions of exhibition
    display and graphic design. Built into the resultant system is
    an implicit absurdity that questions the objectivity of the
    system itself—a systematic critique of systems in the form
    of a system.</p>
  <p>In the same way that the illusion of space within a picture
    plane contradicts the object (i.e. the the stretcher bar defines
    the object itself, while the application of paint defines an
    illusion through paint), the ‘external’ context of exhibition
    co-exists and is in dialogue with the ‘internal’ relations
    between the artworks themselves.  This dialogue between the
    space of exhibition, and the artworks within that space is
    informed by montage—where the process of selecting, editing,
    or piecing together separate objects form a continuous whole—often
    employed as a montage of spatial disorientation in order
    to support psychological disorientation.  Disorientation that
    intends to disrupt the spectacle culture that we endure
    in everyday life.</p>
  <p>Experienced in real-time these installations of paintings,
    photographs, and sculptures request that an observer slow down
    the onslaught of images that we experience daily: both online
    and in real life. Improvised responses to architectural details
    or idiosyncrasies of the physical space of exhibition are
    integral to these systems. Often the exhibitions emphasize
    details of interior architecture that counter the conventions
    of exhibition display, which typically frame the gallery as
    a ‘white cube’. For example, the wrap-around wall drawing at
    Venice6114 that subtlety enhanced the various mismatched
    levels of the gallery floor: for some it went unnoticed, for
    others this gesture appeared as a false reveal, and yet for
    others it evoked an imaginary flood line.</p>
  <p>Currently Kersulis is exploring these concepts and maneuvers
    within the contexts of non-physical spaces. Theoretically
    the internet is an infinite space, but our engagement with
    its contents is finite and defined by our individual identity
    and by our physical interactions with it. Limited by these
    real-life, physical engagements with the ‘space’ of the
    internet, the limitlessness becomes an illusion.</p>

  <ul class='acquaint list root'>
    <li><a class=email href=mailto:nickersulis@yahoo.com>
      nickersulis@yahoo.com</a></li>
    <li><a href={{ url_for('kersulis_main.acquaint') }}>
      artist's bio
    </a></li>
    <li><a href={{ url_for('kersulis_main.network') }}>
      network
    </a></li>
    <li><a href={{ url_for('kersulis_main.acknowledgments') }}>
      acknowledgments
    </a></li>

  </ul>
{% endblock %}

kersulis/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'includes/meta.html' %}
  <title>Nicholas Kersulis{% block title %}{% endblock %}</title>
  {% include 'includes/typekit.html' %}
  {% block head_css %}
    <link rel=stylesheet href={{ url_for('static', filename='css/main.css') }}?6>
  {% endblock %}
  {% assets 'img_favicon' %}
  <link rel=icon
        type=image/png
        href={{ ASSET_URL }} >
  {% endassets %}
</head>
<body>
{% block body %}
<div class="wrap site">
  <header>
    <h1><a href={{ url_for('kersulis_main.index') }}>Nicholas Kersulis</a>
    </h1><span>
    <a href={{ url_for('kersulis_main.acquaint') }}>?</a></span>
  </header>
  <main class=cf>
    {% block main %}{% endblock %}
  </main>
  <footer>
    {% block footer %}
    <small>
      all content copyright &copy; 2018 Nicholas Kersulis, except where noted.
    </small>
    {% endblock %}
  </footer>
</div>
{% endblock %}
{% block bodyjs %}{% endblock %}
</body>
</html>

kersulis/templates/humans.html
{% extends 'base.html' %}
{% block robots %}<meta name=robots content=noindex>
<meta name=googlebot content=noindex>{% endblock %}
{% block body %}
<div class="wrap site" style=padding-top:2em>

  <p>This site was built in the northwest side of Chicago
    during the late summer of 2018. Artwork and writing was
    supplied by Nicholas Kersulis. Design, development,
    and editing was supplied by Nathan Matteson.

  <p>Many clean dishes and even more laughs were
    supplied by Barbara Raidl. An incredibly important
    computer charger was supplied through USPS by
    Sergio Torres-Torres. But it wasn't important after
    all due to another charger supplied by Shiro Akiyoshi.
    Morris Fuller Benton supplied a wicked typeface. Woodbury
    University supplied a grant to help make it possible.</p>

  <p><a lang=pl href=https://www.youtube.com/watch?v=-1-z48cJDbc>
    Chleb</a> is Polish for bread.</p>

  <ul class="humans list root">
    <li><a>Nicholas Kersulis / kersulis.com / Los Angeles CA</a></li>
    <li><a>Nathan Matteson \ skeptic.ist \ obstructures.org \ Chicago IL</a></li>
  </ul>

</div>
{% endblock %}

kersulis/templates/includes/meta.html
<meta charset=UTF-8>
<meta name=viewport content='width=device-width, initial-scale=1.0'>

<meta http-equiv=Content-Security-Policy
      content="default-src 'self';
      script-src 'self' d3js.org 'unsafe-inline' *.typekit.net;
      img-src 'self' *.typekit.net;
      font-src *.typekit.net;
      style-src 'self' 'unsafe-inline'">
{% block robots %}<meta name=robots content=index,follow>
<meta name=googlebot content=index,follow>{% endblock %}
<meta name=format-detection content='telephone=no'>

<meta name=HandheldFriendly content=True>
<meta name=MobileOptimized content=320>

<link rel=canonical href={{ request.url }}>
<link rel=author href={{ url_for('kersulis_main.humans') }}>
<link rel=license href={{ url_for('kersulis_main.copyright') }}>

<meta name=description content='The online portfolio of LA-based visual artist Nicholas Kersulis'>

<meta property=og:site_name content='Nicholas Kersulis'>
<meta property=og:image content='{{ request.host }}{{ url_for('images.crop',
           filename='projects/{}/02RedBlue Mirror_Greycard.jpg'.format('greyscale'),
           width=image_width,
           quality=image_quality) }}'>
<meta property=og:type content=website />

<meta name=twitter:image content='{{ request.host }}{{ url_for('images.crop',
           filename='projects/{}/02RedBlue Mirror_Greycard.jpg'.format('greyscale'),
           width=image_width,
           quality=image_quality) }}'>
<meta name=twitter:image:alt content='Nicholas Kersulis experimenting with chroma and value.'>
<meta name=twitter:card content=summary_large_image>

kersulis/templates/includes/online_work.html
<ul>
  <li class=workpiece>
    <a href={{ url_for('kersulis_main.construction') }}>
      coming soon
{#      the daylight grew dim and when candles were lit the glass#}
{#      of the windows became dark, shutting out the landscape#}
{#      as the walls defied its expanse.#}
    </a></li>
</ul>

kersulis/templates/includes/physical_work.html
<ul>

  <li class=workpiece>
    <a href={{ url_for('kersulis_main.project',
               _project='greyscale') }}>
      the image-world will outlast us all
    </a></li>

  <li class=workpiece>
    <a href={{ url_for('kersulis_main.project',
               _project='monochrome_intervention') }}>
      monochrome intervention
    </a></li>

  <li class=workpiece>
    <a href={{ url_for('kersulis_main.project',
               _project='within_without') }}>
      within without the space of a corner
    </a></li>

{#  <li class=workpiece><a>#}
{#    film series</a>#}
{#    <ul>#}

      <li class=workpiece>
        <a href={{ url_for('kersulis_main.project',
                   _project='mind_your_manners_asshole') }}>
          mind your manners, asshole
        </a></li>

      <li class=workpiece>
        <a href={{ url_for('kersulis_main.project',
                   _project='what_sexual_revolution') }}>
          what sexual revolution?
        </a></li>

      <li class=workpiece>
        <a href={{ url_for('kersulis_main.project',
                     _project='anarchy_love_spectacle') }}>
          anarchy/love/spectacle
        </a></li>

{#    </ul></li>#}

  <li class=workpiece>
    <a href={{ url_for('kersulis_main.project',
               _project='everyday_objects') }}>
      everyday objects for a table
    </a></li>

  <li class=workpiece>
    <a href={{ url_for('kersulis_main.project',
               _project='circular_panels') }}>
      circular panels
{#      <span class=date>2008</span>#}
    </a></li>

</ul>

kersulis/templates/includes/typekit.html
<script>
  // [Typekit Cache](https://github.com/morris/typekit-cache)
  !function(e,t,n,a,c,l,m,o,d,f,h,i){c[l]&&(d=e.createElement(t),d[n]=c[l],e[a]("head")[0].appendChild(d),e.documentElement.className+=" wf-cached"),function s(){for(d=e[a](t),f="",h=0;h<d.length;h++)i=d[h][n],i.match(m)&&(f+=i);f&&(c[l]="/**/"+f),setTimeout(s,o+=o)}()}(document,"style","innerHTML","getElementsByTagName",localStorage,"tk",/^@font|^\.tk-/,100);
</script>
<script>
  (function(d) {
    var config = {
      kitId: 'ulr1olm',
      scriptTimeout: 3000,
      async: true
    },
    h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
  })(document);
</script>

kersulis/templates/index.html
{% extends 'base.html' %}
{% block main %}
<ul class='worklist list root'>
  <li class=worktype>
    <h2><a>
      physical work
    </a></h2>
    {% include 'includes/physical_work.html' %}
  </li>
  <li class=worktype>
    <h2><a>
      online work
    </a></h2>
    {% include 'includes/online_work.html' %}
  </li>
</ul>
{% endblock %}
{% block bodyjs %}
{#  <script src="https://d3js.org/d3.v4.min.js"></script>#}
{#  <script src={{ url_for('static', filename='js/main.js') }}?3></script>#}
{% endblock %}

kersulis/templates/projects/anarchy_love_spectacle.html
{% extends 'base.html' %}
{% block title %}: anarchy/love/spectacle{% endblock %}
{% block main %}
  <div class=work>

{#    <h2>anarchy/love/spectacle</h2>#}

    <p><i>anarchy/love/spectacle</i> is both a film series and a
      ‘movie poster’ that celebrates twenty-two films that
      depict rebellious and anarchistic collective behavior,
      or focus on an individual subject’s interior psychological
      struggle. Set up as a continuous series of films, the
      40-hour screening is shown over a period of days. The
      opening and closing of the venue may interrupt the screening
      of one of the films and, when this occurs, the film will be
      picked up where it left off the day before. The interior
      of the exhibition room is darkened for the projection of
      the films, and an exterior wall of the darkened space
      supports a ‘movie poster,’ which is painted on canvas and
      riveted so that it can be easily transported and reinstalled.</p>

    <p>The historical importance of the films in <i>a/l/s</i>
      is without doubt, but the films I chose also hold personal
      memories. Unlike film series that appear to offer an
      ‘objective survey’ of a particular genre or period,
      autobiographical factors led me to this group of films.
      For cinephiles and record collectors alike, pop culture
      plays an important role in self-discovery, and my subjective
      experience of the films in the series became the final
      determinant in choosing them.</p>

    <p>The films are shown in reverse chronology, with regard to
      the era they depict rather than the era they were made.
      Godard’s <i>Alphaville</i> begins the series because it
      exists in a continuous present, or the forever distant future,
      depending on how one sees things today. Contrast this to
      Luchino Visconti’s epic <i>The Leopard</i>—a period film made
      in the 1960s which takes place a century beforehand in the
      1860s—divulges as much about the counterculture at the time
      of its making as the period it represents.</p>

    <p>No matter the historicity of an event, our personal
      experience with representation influences, even though
      we may remain unaware, how we internalize these events
      as facts. The like-mindedness that forms around
      representations of events, even among strangers,
      is unavoidable.</p>

    <figure>
      <img src={{ url_for('images.crop',
           filename='projects/{}/ALS_Install_2006.jpg'.format(project),
           width=image_width,
           quality=image_quality) }}
           alt>
      <figcaption>
        <i>anarchy/love/spectacle</i> installed at New Langton Arts,
          San Francisco, California
      </figcaption></figure>

    <figure>
      <img src={{ url_for('images.crop',
           filename='projects/{}/ALS_overall-canvas.jpg'.format(project),
           width=image_width,
           quality=image_quality) }}
           alt>
      <figcaption>
        <i>anarchy/love/spectacle</i> (movie poster); acrylic paint and
        gesso on canvas with grommets; 81 &times; 81”
      </figcaption>
    </figure>

  </div>
{% endblock %}

kersulis/templates/projects/circular_panels.html
{% extends 'base.html' %}
{% block title %}: circular panels{% endblock %}
{% block main %}
  <div class=work>

    <p>The physical framework of <i>circular panels</i> is a wall
      constructed at a diagonal within the exhibition space.
      One side of the wall is painted a neutral, pale grey,
      upon which eleven circular, white Plexiglas panels,
      themselves painted with multiple gestures of white gesso,
      spread across from one end to the other. Each circular
      panel is screwed into the wall through its center—the fastener
      left visible to denote each panel’s geometric center and
      the imbalance among and within them, as the center of each
      gesture shifts from left to right on the x-axis. Studio
      photographs of the panels are mounted onto thick Plexiglas
      squares that hang directly on the opposing side of the
      freestanding wall. The photographs occupy an ambiguous
      space somewhere between product photography and fine art
      documentation.</p>

    <figure>
      <img src={{ url_for('images.crop',
           filename='projects/{}/01Circular Panels_Houston.jpg'.format(project),
           width=image_width,
           quality=image_quality) }}
           alt>
      <figcaption>
        <i>circular panels</i> installed at the Blaffer Art Museum,
        Houston, Texas, 2008; free standing wall, 8 &times; 13’ one
        side painted white, the other grey; gesso on 1/16” plexiglas
        circles that are 12” diameter; fastener; c-prints mounted
        onto 3/4” plexiglas panels, each 13” square
      </figcaption></figure>

    <figure>
      <img src={{ url_for('images.crop',
           filename='projects/{}/05Circular Panels_ 16to1_Photos.jpg'.format(project),
           width=image_width,
           quality=image_quality) }}
           alt>
      <figcaption>
        <i>circular panels</i> (verso)
      </figcaption>
    </figure>

    <figure>
      <img src={{ url_for('images.crop',
           filename='projects/{}/03Circular Panels_detail_photo.jpg'.format(project),
           width=image_width,
           quality=image_quality) }}
           alt>
      <figcaption>
        <i>circular panels</i> (verso), detail
      </figcaption>
    </figure>

    <figure>
      <img src={{ url_for('images.crop',
           filename='projects/{}/06Circular Panels_16to1_gesso.jpg'.format(project),
           width=image_width,
           quality=image_quality) }}
           alt>
      <figcaption>
        <i>circular panels</i> (recto)
      </figcaption>
    </figure>

    <figure>
      <img src={{ url_for('images.crop',
           filename='projects/{}/04Circular panels_detail_gesso.jpg'.format(project),
           width=image_width,
           quality=image_quality) }}
           alt>
      <figcaption>
        <i>circular panels</i> (recto), detail
      </figcaption>
    </figure>

  </div>
{% endblock %}

kersulis/templates/projects/greyscale.html
{% extends 'base.html' %}
{% block title %}: the image-world will outlast us all{% endblock %}
{% block main %}
  <div class=work>

    <blockquote>It was formerly believed that if all material things
      disappeared out of the universe, time and space would
      be left. According to relativity theory, however, time
      and space disappear together with the things.</blockquote>

    <p>And so in 1921, <cite>Albert Einstein</cite> explained his theory
      of relativity with a ‘joke’. It continues to fascinate
      that words, space, time, and events are inextricable.
      Art activates events: it conflates our perceptions of
      the external world with inner shifts in our thinking
      and our views of history. <i>The image-world</i> (a proposal
      for an exhibition) takes the concept of the grey scale
      from photography and brings it into real-life. It fuses
      together painted abstractions dependent upon variations
      in tone with photographs: color photographs that
      represent subject matter that naturally exists within
      the grey scale, such as a newspaper clipping photographed
      on a grey wall or a re-photographed black & white print.</p>

    <p><i>stereoscopic greyscale_13</i> (pictured below) uses a
      range of colors pulled from a Kodak grey scale card.
      Ideally, five photographs would be accompanied by five
      <i><a href={{ url_for('kersulis_main.project',
                    _project='monochrome_intervention') }}>
              monochrome interventions</a></i>
      installed throughout a gallery: blackest
      black, white, nearly black, nearly white, and a middle
      grey. Added to these paired
      <i><a href={{ url_for('kersulis_main.project',
                    _project='monochrome_intervention') }}>
              monochrome interventions</a></i> and photographs
      would be greyscale pendant pairs such as the one
      pictured and a large scale painting that competes
      with the architecture.</p>

    <figure>
      <img src={{ url_for('images.crop',
           filename='projects/{}/01StereoscopicGreyscale_13.jpg'.format(project),
           width=image_width,
           quality=image_quality) }}
           alt>
      <figcaption>
        <i>stereoscopic greyscale_13</i> 2018; acrylic on linen;
        each canvas 24 &times; 44”, hung two inches apart
        one atop the other
      </figcaption></figure>

    <figure>
      <img src={{ url_for('images.crop',
           filename='projects/{}/02RedBlue Mirror_Greycard.jpg'.format(project),
           width=image_width,
           quality=image_quality) }}
           alt>
      <figcaption>
        locating a medium grey
      </figcaption></figure>

  </div>
{% endblock %}

kersulis/templates/projects/mind_your_manners_asshole.html
{% extends 'base.html' %}
{% block title %}: mind your manners, asshole{% endblock %}
{% block main %}
  <div class=work>

    <p>The title for this film series is a phrase that stood out
      after reading Ascent of the <i>A-Word: Assholism, the First
        Sixty Years (2012)</i>, by <cite>Geoffrey Nunberg</cite>, who points
      to the <q>paradoxical irony</q> in rudely pointing out
      others’ rudeness that is at the core of the phrase.
      <cite>Nunberg</cite> expands upon the <q>asshole-baiting
        style of political discourse</q>, linking it to
      (amongst many other factors) the personalization of political
      discourse, the technology of modern communication, and to
      a collective character disorder. The increased usage of
      ‘asshole’ during the late 20th c. parallels the takeover
      of counter culture by commercial pop culture at the
      century’s end.</p>

    <p>The films listed for this series are bound to my understanding
      of counter culture and its influence on art, social concerns,
      and politics. After years of watching, reading, and listening
      to art related to counter culture, it has become clear that the
      historical precedents that spawned this counter culture, the
      contexts that it left behind, and the detritus that have
      taken its place have all became obstacles in the realization
      of much of my work.</p>

    <p></p>

    <figure>
      <img src={{ url_for('images.crop',
           filename='projects/{}/MYMA_overall canvas_preview.jpeg'.format(project),
           width=image_width,
           quality=image_quality) }}
           alt>
      <figcaption>
        <i>mind your manners, asshole</i> (movie poster); acrylic paint
        on canvas with grommets; 81 × 81"
      </figcaption></figure>

    <figure>
      <img src={{ url_for('images.crop',
           filename='projects/{}/MYMA_detail_preview.jpeg'.format(project),
           width=image_width,
           quality=image_quality) }}
           alt>
      <figcaption>
        <i>mind your manners, asshole</i> (movie poster) detail
      </figcaption>
    </figure>

  </div>
{% endblock %}

kersulis/templates/under_construction.html
{% extends 'base.html' %}
{% block main %}
  <img src={{ url_for('static', filename='images/digger.gif') }}
       alt style="display:block;margin:2em auto">
{% endblock %}